# Set the base image to use for the container
FROM openjdk:11-jre-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the application WAR file to the container
COPY target/CarApp.war /app

# Expose the default port for the application
EXPOSE 8080

# Set the command to run when the container starts
CMD ["java", "-jar", "CarApp.war"]
